export const CREATE_POKEMON = 'CREATE_POKEMON';
export const CREATE_POKEMON_SUCCESS = 'CREATE_POKEMON_SUCCESS';
export const CREATE_POKEMON_ERROR = 'CREATE_POKEMON_ERROR';

export const READ_POKEMONS = 'READ_POKEMONS';
export const READ_POKEMONS_SUCCESS = 'READ_POKEMONS_SUCCESS';
export const READ_POKEMONS_ERROR = 'READ_POKEMONS_ERROR';