export const READ_POKEMONS = 'READ_POKEMONS';
export const READ_POKEMONS_SUCCESS = 'READ_POKEMONS_SUCCESS';
export const READ_POKEMONS_ERROR = 'READ_POKEMONS_ERROR';

export const READ_POKEMON = 'READ_POKEMON';
export const READ_POKEMON_SUCCESS = 'READ_POKEMON_SUCCESS';
export const READ_POKEMON_ERROR = 'READ_POKEMON_ERROR';

export const UPDATE_POKEMON = 'UPDATE_POKEMON';
export const UPDATE_POKEMON_SUCCESS = 'UPDATE_POKEMON_SUCCESS';
export const UPDATE_POKEMON_ERROR = 'UPDATE_POKEMON_ERROR';

export const DELETE_POKEMON = 'DELETE_POKEMON';
export const DELETE_POKEMON_SUCCESS = 'DELETE_POKEMON_SUCCESS';
export const DELETE_POKEMON_ERROR = 'DELETE_POKEMON_ERROR';