export const UPDATE_POKEMON = 'UPDATE_POKEMON';
export const UPDATE_POKEMON_SUCCESS = 'UPDATE_POKEMON_SUCCESS';
export const UPDATE_POKEMON_ERROR = 'UPDATE_POKEMON_ERROR';

export const DELETE_POKEMON = 'DELETE_POKEMON';
export const DELETE_POKEMON_SUCCESS = 'DELETE_POKEMON_SUCCESS';
export const DELETE_POKEMON_ERROR = 'DELETE_POKEMON_ERROR';